#!/bin/bash

###############################################################################
# ENV definition
###############################################################################

VIM_CONF="$HOME/.vimrc"
VIM_A_PLUGIN="$HOME/.vim/plugin/a.vim"
TMUX_CONF="$HOME/.tmux.conf"
FISH_CONF="$HOME/.config/fish"
YCM_CONF="$HOME/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"

BACKUP_DIR="./.config"

###############################################################################
# backup config file
# .vimrc, .tmux.conf, fish
###############################################################################
function backup()
{
  set -x
  cp -r "$FISH_CONF"    "$BACKUP_DIR"
  cp    "$VIM_CONF"     "$BACKUP_DIR"
  cp    "$VIM_A_PLUGIN" "$BACKUP_DIR"
  cp    "$TMUX_CONF"    "$BACKUP_DIR"
  cp    "$YCM_CONF"     "$BACKUP_DIR"
}

function push()
{
  git add .
  git commit -m "$1"
  git push origin master
}

case "$1" in
  backup)
    backup
    ;;

  push)
    if [ "$#" -ne 2 ]; then
      echo -e "no commit message\nusage: ./config.sh push <msg> [branch]"
      exit 2
    fi
    push "$2"
    ;;

  *)
    echo -e $"Usage: $0 { backup | push <msg> [branch] }"
    exit 1
esac
